export const STREAMING_PLATFORMS = [
    "Amazon Channel",
    "Amazon Video",
    "Apple TV",
    "Apple TV Channel",
    "Apple TV+",
    "BroadwayHD",
    "Claro video",
    "Crunchyroll",
    "Cultpix",
    "Curiosity Stream",
    "DIRECTV GO",
    "Disney+",
    "DocAlliance",
    "Eventive",
    "FilmBox+",
    "Filmzie",
    "Google Play",
    "GuideDoc",
    "Hoichoi",
    "Kocowa",
    "Magellan TV",
    "Max",
    "Microsoft Store",
    "MovistarTV",
    "MUBI",
    "Netflix",
    "Nuestro Cine MX",
    "Paramount+",
    "Pluto TV",
    "Prime Video",
    "Runtime",
    "Sun Nxt",
    "Tubi TV",
    "VIX",
    "WOW Presents +",
    "YouTube Premium",
];
